name: Composer

on:
  pull_request:
  push:
    branches:
      - master
      - stable*

jobs:
  php:
    runs-on: ubuntu-latest
  
    name: Check vendor changes
    steps:
    - name: Checkout
      uses: actions/checkout@master
    - name: Set up php
      uses: shivammathur/setup-php@master
      with:
        php-version: 7.4
        coverage: none
    - name: Install dependencies
      run: composer install --no-dev
    - name: Remove ignored files
      run: git clean -xf
    - name: Update autoloader
      run: composer dump-autoload
    - name: Check vendor changes
      run: |
        bash -c "[[ ! \"`git status --porcelain `\" ]] || ( echo 'Uncommited vendor changes' && git status && exit 1 )"
